#!/usr/bin/env python3

import json
import os
import re
import sys
import time
from datetime import datetime, timezone

import requests


OPENROUTER_URL = "https://openrouter.ai/api/v1/chat/completions"
OPENROUTER_MODEL = "openrouter/free"

CONNECT_TIMEOUT = 15
READ_TIMEOUT = 60

MAX_API_ATTEMPTS = 3
RETRY_DELAYS = [30, 60]

OUTPUT_FILE = "source/vtuber-readings.json"

ALLOWED_STATUS = {"verified", "review", "unknown"}
ALLOWED_CONFIDENCE = {"high", "medium", "review", "unknown"}
ALLOWED_SOURCE_TYPES = {
    "official",
    "wikipedia",
    "vtuber_database",
    "media",
    "other",
    "",
}


KANA_ONLY_RE = re.compile(r"^[\u3040-\u309f\u30a0-\u30ff・ー]+$")


def utc_now():
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat().replace(
        "+00:00", "Z"
    )


def log(message):
    print(message, file=sys.stderr, flush=True)


def is_kana_only_name(name):
    return bool(name) and bool(KANA_ONLY_RE.fullmatch(name))


def kana_to_reading(name):
    reading_chars = []

    for char in name:
        codepoint = ord(char)

        if char == "・":
            continue

        if "\u30a1" <= char <= "\u30f6":
            char = chr(codepoint - 0x60)

        reading_chars.append(char)

    return "".join(reading_chars)


def make_deterministic_result(uuid, name):
    reading = kana_to_reading(name)

    if not reading:
        raise ValueError("Kana-only name produced an empty reading")

    checked_at = utc_now()

    return {
        "uuid": uuid,
        "name": name,
        "reading": reading,
        "source": "deterministic:kana-only",
        "source_type": "other",
        "confidence": "high",
        "status": "verified",
        "notes": "name.jp is kana-only; reading was generated by deterministic kana conversion. Middle dot was not read.",
        "checked_at": checked_at,
        "last_attempted_at": checked_at,
        "last_attempt_result": "success",
    }


def make_failure_record(uuid, name, started_at, existing=None):
    notes = ""

    if isinstance(existing, dict):
        notes = existing.get("notes", "")

    return {
        "uuid": uuid,
        "name": name,
        "reading": "",
        "source": "",
        "source_type": "",
        "confidence": "unknown",
        "status": "pending",
        "notes": notes,
        "checked_at": "",
        "last_attempted_at": started_at,
        "last_attempt_result": "error",
    }


def load_results():
    if not os.path.exists(OUTPUT_FILE):
        return []

    with open(OUTPUT_FILE, "r", encoding="utf-8") as f:
        data = json.load(f)

    if not isinstance(data, list):
        raise ValueError(f"{OUTPUT_FILE} must contain a JSON array")

    return data


def save_results(results):
    temp_file = OUTPUT_FILE + ".tmp"

    with open(temp_file, "w", encoding="utf-8") as f:
        json.dump(
            results,
            f,
            ensure_ascii=False,
            indent=2,
        )
        f.write("\n")

    os.replace(temp_file, OUTPUT_FILE)


def upsert_result(record):
    results = load_results()

    uuid = record["uuid"]

    for i, existing in enumerate(results):
        if existing.get("uuid") == uuid:
            results[i] = record
            save_results(results)
            return

    results.append(record)
    save_results(results)


def get_existing_result(uuid):
    results = load_results()

    for record in results:
        if record.get("uuid") == uuid:
            return record

    return None


def extract_json_object(text):
    """
    Extract a JSON object from the AI response.

    Accepts:
    - pure JSON
    - JSON inside a Markdown code fence
    - JSON surrounded by accidental prose

    Does NOT invent or repair missing JSON.
    """

    if not isinstance(text, str):
        raise ValueError("AI response content is not a string")

    text = text.strip()

    if not text:
        raise ValueError("AI response content is empty")

    try:
        parsed = json.loads(text)

        if isinstance(parsed, dict):
            return parsed

        raise ValueError("AI response JSON is not an object")

    except json.JSONDecodeError:
        pass

    fenced = re.search(
        r"```(?:json)?\s*(\{.*?\})\s*```",
        text,
        flags=re.DOTALL | re.IGNORECASE,
    )

    if fenced:
        candidate = fenced.group(1)

        try:
            parsed = json.loads(candidate)

            if isinstance(parsed, dict):
                return parsed

        except json.JSONDecodeError as exc:
            raise ValueError(
                f"JSON code fence found but JSON is invalid: {exc}"
            ) from exc

    start = text.find("{")

    if start >= 0:
        depth = 0
        in_string = False
        escaped = False

        for i in range(start, len(text)):
            char = text[i]

            if in_string:
                if escaped:
                    escaped = False
                elif char == "\\":
                    escaped = True
                elif char == '"':
                    in_string = False
                continue

            if char == '"':
                in_string = True
                continue

            if char == "{":
                depth += 1

            elif char == "}":
                depth -= 1

                if depth == 0:
                    candidate = text[start : i + 1]

                    try:
                        parsed = json.loads(candidate)

                        if isinstance(parsed, dict):
                            return parsed

                    except json.JSONDecodeError as exc:
                        raise ValueError(
                            f"Embedded JSON object is invalid: {exc}"
                        ) from exc

        raise ValueError("Could not find a complete valid JSON object")

    raise ValueError("No JSON object found in AI response")


def build_prompt(uuid, name):
    return f"""
You are researching the VTuber record below.

TARGET
name: {name}
uuid: {uuid}

Your task is to determine the actual Japanese pronunciation/reading of this exact VTuber name.

IMPORTANT IDENTITY RULES
- The UUID is the stable identity key.
- Do not confuse similarly named VTubers.
- Do not confuse a VTuber with another person, character, organization, or unrelated account.
- Do not infer a reading merely from kanji.
- Do not guess.
- The source must support the reading for this exact VTuber.
- Search the web when necessary.
- Prefer official sources first.
- Wikipedia is an acceptable high-quality secondary source.
- Established VTuber databases are acceptable secondary sources.
- Established Japanese media/reference sites are acceptable secondary sources.
- Do not rely on search-result snippets alone.
- Do not rely on a source merely because the name looks similar.
- Stop searching once sufficient reliable evidence has been obtained.
- Do not perform unlimited or unnecessary searches.

SOURCE PRIORITY
1. Official VTuber / agency / creator source
2. Wikipedia
3. Established VTuber database
4. Established Japanese media or reference source
5. Other identifiable source

CRITICAL OUTPUT RULE

You MUST return exactly ONE valid JSON object as your final answer.

DO NOT return:
- investigation notes
- explanations
- progress messages
- "I found..."
- "Let me search..."
- "I will check..."
- "I have gathered..."
- "I need to search..."
- Markdown
- code fences
- prose before the JSON
- prose after the JSON
- partial results
- search progress

Web searching and reasoning are internal steps.

The ONLY text in your final response must be the JSON object.

The JSON object MUST contain exactly these fields:

{{
  "uuid": "{uuid}",
  "name": "{name}",
  "reading": "",
  "source": "",
  "source_type": "",
  "confidence": "unknown",
  "status": "unknown",
  "notes": ""
}}

FIELD RULES

- uuid:
  Must be exactly "{uuid}".

- name:
  Must be exactly "{name}".

- reading:
  The actual Japanese pronunciation if reliably established.
  If no reliable reading can be established, use "".
  Never guess.

- source:
  A URL or concise source identification supporting the reading.
  If no reliable source exists, use "".

- source_type:
  Must be one of:
  "official"
  "wikipedia"
  "vtuber_database"
  "media"
  "other"
  ""

- confidence:
  Must be one of:
  "high"
  "medium"
  "review"
  "unknown"

- status:
  Must be one of:
  "verified"
  "review"
  "unknown"

- notes:
  Short factual note only.
  Do not include research logs.
  Do not include long explanations.
  If there is no useful note, use "".

STATUS RULES

- verified:
  Reliable evidence establishes the reading.

- review:
  A plausible candidate exists, but evidence is insufficient, weak, or conflicting.

- unknown:
  No reliable reading can be established.

Never invent a reading merely to avoid returning "unknown".

CONFIDENCE RULES

- high:
  Strong direct evidence, preferably from an official source or multiple reliable sources.

- medium:
  Reliable secondary evidence, including Wikipedia or an established VTuber database.

- review:
  Weak, conflicting, or incomplete evidence.

- unknown:
  No reliable evidence for a reading.

IMPORTANT

If Wikipedia provides a reliable reading but there is no official confirmation,
it may support "medium" confidence.

If an established VTuber database provides a reliable reading,
it may support "medium" confidence.

Do not automatically assign "high" merely because a source exists.

FINAL VALIDATION BEFORE ANSWERING

Before producing the final answer:

1. Confirm the identity matches the exact target name.
2. Confirm the identity matches the exact UUID when the source provides UUID information.
3. Confirm the reading is supported by evidence.
4. Confirm the JSON is syntactically valid.
5. Confirm every required field exists.
6. Confirm all enum values are valid.
7. Confirm uuid is exactly "{uuid}".
8. Confirm name is exactly "{name}".
9. Confirm there is absolutely no prose outside the JSON object.

If reliable evidence cannot be established, return a valid JSON object with:
- reading = ""
- confidence = "unknown"
- status = "unknown"

Do not explain the failure outside the JSON.

Return ONLY the JSON object.
""".strip()


def validate_result(data, uuid, name):
    if not isinstance(data, dict):
        raise ValueError("AI response is not a JSON object")

    required_fields = {
        "uuid",
        "name",
        "reading",
        "source",
        "source_type",
        "confidence",
        "status",
        "notes",
    }

    missing = required_fields - set(data.keys())

    if missing:
        raise ValueError(
            f"AI JSON missing required fields: {sorted(missing)}"
        )

    if data["uuid"] != uuid:
        raise ValueError(
            f"UUID mismatch: expected={uuid!r} actual={data['uuid']!r}"
        )

    if data["name"] != name:
        raise ValueError(
            f"name mismatch: expected={name!r} actual={data['name']!r}"
        )

    if not isinstance(data["reading"], str):
        raise ValueError("reading must be a string")

    if not isinstance(data["source"], str):
        raise ValueError("source must be a string")

    if not isinstance(data["source_type"], str):
        raise ValueError("source_type must be a string")

    if not isinstance(data["confidence"], str):
        raise ValueError("confidence must be a string")

    if not isinstance(data["status"], str):
        raise ValueError("status must be a string")

    if not isinstance(data["notes"], str):
        raise ValueError("notes must be a string")

    if data["status"] not in ALLOWED_STATUS:
        raise ValueError(
            f"Invalid status: {data['status']!r}"
        )

    if data["confidence"] not in ALLOWED_CONFIDENCE:
        raise ValueError(
            f"Invalid confidence: {data['confidence']!r}"
        )

    if data["source_type"] not in ALLOWED_SOURCE_TYPES:
        raise ValueError(
            f"Invalid source_type: {data['source_type']!r}"
        )

    if data["reading"] and not data["source"]:
        raise ValueError(
            "AI returned a reading without a supporting source"
        )

    return data


def request_openrouter_once(uuid, name, prompt, attempt):
    api_key = os.environ.get("OPENROUTER_API_KEY")

    if not api_key:
        raise RuntimeError("OPENROUTER_API_KEY is not set")

    payload = {
        "model": OPENROUTER_MODEL,
        "messages": [
            {
                "role": "user",
                "content": prompt,
            }
        ],
        "response_format": {
            "type": "json_object"
        },
        "tools": [
            {
                "type": "openrouter:web_search"
            }
        ],
    }

    headers = {
        "Authorization": f"Bearer {api_key}",
        "Content-Type": "application/json",
        "HTTP-Referer": "https://github.com/wonderalpha404/vtuber-dictionary",
        "X-Title": "VTuber Dictionary Reading Research",
    }

    log("OPENROUTER REQUEST")
    log(f"name={name}")
    log(f"uuid={uuid}")
    log(f"attempt={attempt}/{MAX_API_ATTEMPTS}")
    log(f"model={OPENROUTER_MODEL}")
    log("web_search=true")
    log(
        f"connect_timeout={CONNECT_TIMEOUT}s "
        f"read_timeout={READ_TIMEOUT}s"
    )
    log(f"max_attempts={MAX_API_ATTEMPTS}")

    started = time.monotonic()

    try:
        response = requests.post(
            OPENROUTER_URL,
            headers=headers,
            json=payload,
            timeout=(CONNECT_TIMEOUT, READ_TIMEOUT),
        )

    except requests.exceptions.ConnectTimeout as exc:
        elapsed = time.monotonic() - started

        log(
            f"OPENROUTER CONNECT TIMEOUT "
            f"name={name} uuid={uuid} "
            f"attempt={attempt}/{MAX_API_ATTEMPTS} "
            f"elapsed={elapsed:.1f}s"
        )

        raise RuntimeError(
            f"OpenRouter connection timeout after {elapsed:.1f}s"
        ) from exc

    except requests.exceptions.ReadTimeout as exc:
        elapsed = time.monotonic() - started

        log(
            f"OPENROUTER READ TIMEOUT "
            f"name={name} uuid={uuid} "
            f"attempt={attempt}/{MAX_API_ATTEMPTS} "
            f"elapsed={elapsed:.1f}s"
        )

        raise RuntimeError(
            f"OpenRouter read timeout after {elapsed:.1f}s"
        ) from exc

    except requests.exceptions.RequestException as exc:
        elapsed = time.monotonic() - started

        log(
            f"OPENROUTER REQUEST ERROR "
            f"name={name} uuid={uuid} "
            f"attempt={attempt}/{MAX_API_ATTEMPTS} "
            f"elapsed={elapsed:.1f}s"
        )

        raise RuntimeError(
            f"OpenRouter request error: {exc}"
        ) from exc

    elapsed = time.monotonic() - started

    log(
        f"OPENROUTER HTTP RESPONSE "
        f"name={name} uuid={uuid} "
        f"attempt={attempt}/{MAX_API_ATTEMPTS} "
        f"status={response.status_code} "
        f"elapsed={elapsed:.1f}s "
        f"bytes={len(response.content)}"
    )

    if response.status_code != 200:
        body_preview = response.text[:1000].replace("\n", "\\n")

        log(
            f"OPENROUTER HTTP ERROR BODY PREVIEW "
            f"name={name} uuid={uuid} "
            f"attempt={attempt}/{MAX_API_ATTEMPTS}: "
            f"{body_preview}"
        )

        raise RuntimeError(
            f"OpenRouter HTTP status {response.status_code}"
        )

    try:
        data = response.json()

    except json.JSONDecodeError as exc:
        body_preview = response.text[:1000].replace("\n", "\\n")

        log(
            f"OPENROUTER RESPONSE JSON PARSE FAILED "
            f"name={name} uuid={uuid} "
            f"attempt={attempt}/{MAX_API_ATTEMPTS}"
        )
        log(
            f"HTTP BODY PREVIEW: {body_preview}"
        )

        raise RuntimeError(
            f"Failed to parse OpenRouter HTTP response as JSON: {exc}"
        ) from exc

    log(
        f"OPENROUTER RESPONSE STRUCTURE "
        f"name={name} uuid={uuid} "
        f"attempt={attempt}/{MAX_API_ATTEMPTS} "
        f"top_level_keys={list(data.keys())}"
    )

    choices = data.get("choices")

    if not isinstance(choices, list) or not choices:
        raise RuntimeError(
            "OpenRouter response contains no choices"
        )

    log(
        f"OPENROUTER CHOICES "
        f"name={name} uuid={uuid} "
        f"attempt={attempt}/{MAX_API_ATTEMPTS} "
        f"count={len(choices)}"
    )

    message = choices[0].get("message")

    if not isinstance(message, dict):
        raise RuntimeError(
            "OpenRouter response contains no message object"
        )

    log(
        f"OPENROUTER MESSAGE FOUND "
        f"name={name} uuid={uuid} "
        f"attempt={attempt}/{MAX_API_ATTEMPTS} "
        f"message_keys={list(message.keys())}"
    )

    refusal = message.get("refusal")

    if refusal:
        log(
            f"OPENROUTER REFUSAL "
            f"name={name} uuid={uuid} "
            f"attempt={attempt}/{MAX_API_ATTEMPTS} "
            f"refusal={str(refusal)[:1000]}"
        )

        raise RuntimeError(
            "OpenRouter returned a refusal"
        )

    content = message.get("content")

    if not isinstance(content, str):
        raise RuntimeError(
            "OpenRouter message content is not a string"
        )

    log(
        f"OPENROUTER AI CONTENT RECEIVED "
        f"name={name} uuid={uuid} "
        f"attempt={attempt}/{MAX_API_ATTEMPTS} "
        f"content_length={len(content)}"
    )

    return content


def request_openrouter(uuid, name, prompt):
    last_error = None

    for attempt in range(1, MAX_API_ATTEMPTS + 1):
        try:
            return request_openrouter_once(
                uuid=uuid,
                name=name,
                prompt=prompt,
                attempt=attempt,
            )

        except Exception as exc:
            last_error = exc

            log(
                f"OPENROUTER ATTEMPT FAILED "
                f"name={name} uuid={uuid} "
                f"attempt={attempt}/{MAX_API_ATTEMPTS} "
                f"error_type={type(exc).__name__} "
                f"message={exc}"
            )

            if attempt >= MAX_API_ATTEMPTS:
                log(
                    f"OPENROUTER ALL ATTEMPTS FAILED "
                    f"name={name} uuid={uuid} "
                    f"attempts={MAX_API_ATTEMPTS}"
                )
                raise

            delay = RETRY_DELAYS[attempt - 1]

            log(
                f"OPENROUTER RETRY SCHEDULED "
                f"name={name} uuid={uuid} "
                f"next_attempt={attempt + 1}/{MAX_API_ATTEMPTS} "
                f"wait={delay}s"
            )

            time.sleep(delay)

    raise RuntimeError(
        f"OpenRouter failed after {MAX_API_ATTEMPTS} attempts: {last_error}"
    )


def research(uuid, name):
    started_at = utc_now()

    log("RESEARCH START")
    log(f"uuid={uuid}")
    log(f"RESEARCH TARGET name={name} uuid={uuid}")

    if is_kana_only_name(name):
        log(
            f"DETERMINISTIC KANA-ONLY "
            f"name={name} uuid={uuid} "
            f"ai_call=false "
            f"reason=kana-only"
        )

        try:
            result = make_deterministic_result(
                uuid=uuid,
                name=name,
            )
            upsert_result(result)

            log(
                f"RESULT SAVED "
                f"name={name} "
                f"uuid={uuid} "
                f"reading={result['reading']} "
                f"status={result['status']} "
                f"confidence={result['confidence']}"
            )

            log(
                f"RESEARCH SUCCESS "
                f"name={name} uuid={uuid} "
                f"method=deterministic"
            )

            return 0

        except Exception as exc:
            log(
                f"DETERMINISTIC PROCESSING FAILED "
                f"name={name} uuid={uuid} "
                f"error_type={type(exc).__name__} "
                f"message={exc}"
            )

            existing = None

            try:
                existing = get_existing_result(uuid)
            except Exception as load_exc:
                log(
                    f"EXISTING RESULT LOAD FAILED "
                    f"name={name} "
                    f"uuid={uuid} "
                    f"error_type={type(load_exc).__name__} "
                    f"message={load_exc}"
                )

            if (
                existing is not None
                and existing.get("status") in ALLOWED_STATUS
                and existing.get("last_attempt_result") == "success"
            ):
                log(
                    f"EXISTING SUCCESS RESULT NOT OVERWRITTEN "
                    f"name={name} "
                    f"uuid={uuid} "
                    f"status={existing.get('status')}"
                )

            else:
                failure = make_failure_record(
                    uuid=uuid,
                    name=name,
                    started_at=started_at,
                    existing=existing,
                )

                try:
                    upsert_result(failure)

                    log(
                        f"FAILURE STATE SAVED "
                        f"name={name} "
                        f"uuid={uuid} "
                        f"status=pending "
                        f"last_attempt_result=error"
                    )

                except Exception as save_exc:
                    log(
                        f"FAILURE STATE SAVE FAILED "
                        f"name={name} "
                        f"uuid={uuid} "
                        f"error_type={type(save_exc).__name__} "
                        f"message={save_exc}"
                    )

            log(
                f"RESEARCH FAILED "
                f"name={name} "
                f"uuid={uuid} "
                f"error_type={type(exc).__name__} "
                f"message={exc}"
            )

            return 1

    prompt = build_prompt(uuid, name)

    log(
        f"RESEARCH PROMPT READY "
        f"name={name} uuid={uuid} "
        f"prompt_length={len(prompt)}"
    )

    try:
        content = request_openrouter(
            uuid=uuid,
            name=name,
            prompt=prompt,
        )

        log(
            f"AI RESPONSE RECEIVED "
            f"name={name} "
            f"content_length={len(content)}"
        )

        try:
            data = extract_json_object(content)

        except ValueError as exc:
            log(
                f"AI RESPONSE PARSE FAILED "
                f"name={name} "
                f"error_type=invalid_json"
            )

            preview = content[:1000].replace("\n", "\\n")

            log(
                f"AI RESPONSE START PREVIEW: {preview}"
            )

            if len(content) > 1000:
                end_preview = content[-1000:].replace("\n", "\\n")

                log(
                    f"AI RESPONSE END PREVIEW: {end_preview}"
                )

            raise ValueError(
                "Failed to parse AI response as a JSON object"
            ) from exc

        log(
            f"AI JSON PARSED "
            f"name={name} uuid={uuid}"
        )

        data = validate_result(
            data=data,
            uuid=uuid,
            name=name,
        )

        finished_at = utc_now()

        result = {
            "uuid": data["uuid"],
            "name": data["name"],
            "reading": data["reading"],
            "source": data["source"],
            "source_type": data["source_type"],
            "confidence": data["confidence"],
            "status": data["status"],
            "notes": data["notes"],
            "checked_at": finished_at,
            "last_attempted_at": finished_at,
            "last_attempt_result": "success",
        }

        upsert_result(result)

        log(
            f"RESULT SAVED "
            f"name={name} "
            f"uuid={uuid} "
            f"reading={result['reading']} "
            f"status={result['status']} "
            f"confidence={result['confidence']}"
        )

        log(
            f"RESEARCH SUCCESS "
            f"name={name} uuid={uuid}"
        )

        return 0

    except Exception as exc:
        existing = None

        try:
            existing = get_existing_result(uuid)
        except Exception as load_exc:
            log(
                f"EXISTING RESULT LOAD FAILED "
                f"name={name} "
                f"uuid={uuid} "
                f"error_type={type(load_exc).__name__} "
                f"message={load_exc}"
            )

        if (
            existing is not None
            and existing.get("status") in ALLOWED_STATUS
            and existing.get("last_attempt_result") == "success"
        ):
            log(
                f"EXISTING SUCCESS RESULT NOT OVERWRITTEN "
                f"name={name} "
                f"uuid={uuid} "
                f"status={existing.get('status')}"
            )

        else:
            failure = make_failure_record(
                uuid=uuid,
                name=name,
                started_at=started_at,
                existing=existing,
            )

            try:
                upsert_result(failure)

                log(
                    f"FAILURE STATE SAVED "
                    f"name={name} "
                    f"uuid={uuid} "
                    f"status=pending "
                    f"last_attempt_result=error"
                )

            except Exception as save_exc:
                log(
                    f"FAILURE STATE SAVE FAILED "
                    f"name={name} "
                    f"uuid={uuid} "
                    f"error_type={type(save_exc).__name__} "
                    f"message={save_exc}"
                )

        log(
            f"RESEARCH FAILED "
            f"name={name} "
            f"uuid={uuid} "
            f"error_type={type(exc).__name__} "
            f"message={exc}"
        )

        return 1


def main():
    if len(sys.argv) != 3:
        print(
            "Usage: python scripts/research_one_vtuber.py <uuid> <name>",
            file=sys.stderr,
        )
        return 2

    uuid = sys.argv[1]
    name = sys.argv[2]

    return research(
        uuid=uuid,
        name=name,
    )


if __name__ == "__main__":
    sys.exit(main())
