#!/usr/bin/env python3

import json
import os
import re
import sys
import time
from datetime import datetime, timezone

import requests

OPENROUTER_URL = "https://openrouter.ai/api/v1/chat/completions"
OPENROUTER_MODEL = "openrouter/free"
CONNECT_TIMEOUT = 15
READ_TIMEOUT = 60
MAX_API_ATTEMPTS = 3
RETRY_DELAYS = [30, 60]
OUTPUT_FILE = "source/vtuber-readings.json"
ALLOWED_STATUS = {"verified", "review", "pending"}
ALLOWED_CONFIDENCE = {"high", "medium", "review", "unknown", ""}
ALLOWED_SOURCE_TYPES = {"official", "wikipedia", "vtuber_database", "media", "other", ""}
KANA_ONLY_RE = re.compile(r"^[\u3040-\u309f\u30a0-\u30ff・ー]+$")


def utc_now():
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat().replace("+00:00", "Z")


def log(message):
    print(message, file=sys.stderr, flush=True)


def is_kana_only_name(name):
    return bool(name) and bool(KANA_ONLY_RE.fullmatch(name))


def kana_to_reading(name):
    result = []
    for char in name:
        if char == "・":
            continue
        if "\u30a1" <= char <= "\u30f6":
            char = chr(ord(char) - 0x60)
        result.append(char)
    return "".join(result)


def make_deterministic_result(uuid, name):
    reading = kana_to_reading(name)
    if not reading:
        raise ValueError("Kana-only name produced an empty reading")
    now = utc_now()
    return {
        "uuid": uuid, "name": name, "reading": reading,
        "source": "deterministic:kana-only", "source_type": "other",
        "confidence": "", "status": "verified",
        "notes": "name.jp is kana-only; reading was generated by deterministic kana conversion. Middle dot was not read.",
        "checked_at": now, "last_attempted_at": now,
        "last_attempt_result": "success",
    }


def make_failure_record(uuid, name, started_at, existing=None):
    return {
        "uuid": uuid, "name": name, "reading": "", "source": "",
        "source_type": "", "confidence": "", "status": "pending",
        "notes": existing.get("notes", "") if isinstance(existing, dict) else "",
        "checked_at": "", "last_attempted_at": started_at,
        "last_attempt_result": "technical_error",
    }


def load_results():
    if not os.path.exists(OUTPUT_FILE):
        return []
    with open(OUTPUT_FILE, "r", encoding="utf-8") as f:
        data = json.load(f)
    if not isinstance(data, list):
        raise ValueError(f"{OUTPUT_FILE} must contain a JSON array")
    return data


def save_results(results):
    temp_file = OUTPUT_FILE + ".tmp"
    with open(temp_file, "w", encoding="utf-8") as f:
        json.dump(results, f, ensure_ascii=False, indent=2)
        f.write("\n")
    os.replace(temp_file, OUTPUT_FILE)


def upsert_result(record):
    results = load_results()
    for i, existing in enumerate(results):
        if existing.get("uuid") == record["uuid"]:
            results[i] = record
            save_results(results)
            return
    results.append(record)
    save_results(results)


def get_existing_result(uuid):
    for record in load_results():
        if record.get("uuid") == uuid:
            return record
    return None


def extract_json_object(text):
    if not isinstance(text, str) or not text.strip():
        raise ValueError("AI response content is empty or not a string")
    text = text.strip()
    try:
        parsed = json.loads(text)
        if isinstance(parsed, dict):
            return parsed
    except json.JSONDecodeError:
        pass
    fenced = re.search(r"```(?:json)?\s*(\{.*?\})\s*```", text, flags=re.DOTALL | re.IGNORECASE)
    if fenced:
        parsed = json.loads(fenced.group(1))
        if isinstance(parsed, dict):
            return parsed
    start = text.find("{")
    if start < 0:
        raise ValueError("No JSON object found in AI response")
    depth = 0
    in_string = False
    escaped = False
    for i in range(start, len(text)):
        char = text[i]
        if in_string:
            if escaped:
                escaped = False
            elif char == "\\":
                escaped = True
            elif char == '"':
                in_string = False
            continue
        if char == '"':
            in_string = True
        elif char == "{":
            depth += 1
        elif char == "}":
            depth -= 1
            if depth == 0:
                parsed = json.loads(text[start:i + 1])
                if isinstance(parsed, dict):
                    return parsed
                break
    raise ValueError("Could not find a complete valid JSON object")


def build_prompt(uuid, name):
    return f"""
You are researching the VTuber record below.

TARGET
name: {name}
uuid: {uuid}

Determine the actual Japanese pronunciation/reading of this exact VTuber name.
Do not guess. The source must support the reading for this exact VTuber.
Search the web when necessary. Prefer official sources, then Wikipedia, established VTuber databases, and established Japanese media/reference sources.
Do not rely on search-result snippets alone or confuse similarly named entities.

Return exactly one valid JSON object and no prose. The object must contain exactly these fields:
{{
  "uuid": "{uuid}",
  "name": "{name}",
  "reading": "",
  "source": "",
  "source_type": "",
  "confidence": "unknown",
  "status": "pending",
  "notes": ""
}}

Rules:
- uuid must exactly match the target.
- name should identify the target VTuber, but the returned name is not used as the canonical record name.
- reading is the reliably established Japanese pronunciation; use "" if none can be established.
- source must identify evidence supporting a non-empty reading.
- source_type must be official, wikipedia, vtuber_database, media, other, or "".
- confidence must be high, medium, review, or unknown.
- status must be verified, review, or pending.
- verified means reliable evidence establishes the reading.
- review means a plausible candidate exists but evidence is weak, incomplete, or conflicting.
- pending means no reliable reading can be established.
- high means strong direct evidence; medium means reliable secondary evidence; review means weak/conflicting evidence; unknown means no reliable evidence.
- If status is pending, reading/source/source_type must be empty and confidence must be unknown.
- If status is verified, confidence must be high or medium and reading/source must be non-empty.
- If status is review, confidence must be review and reading may be non-empty only when a plausible candidate is supported.
- Never invent a reading merely to avoid pending.
""".strip()


def validate_result(data, uuid, name):
    required = {"uuid", "name", "reading", "source", "source_type", "confidence", "status", "notes"}
    if not isinstance(data, dict):
        raise ValueError("AI response is not a JSON object")
    missing = required - set(data.keys())
    if missing:
        raise ValueError(f"AI JSON missing required fields: {sorted(missing)}")
    if data["uuid"] != uuid:
        raise ValueError(f"UUID mismatch: expected={uuid!r} actual={data['uuid']!r}")
    for field in ("name", "reading", "source", "source_type", "confidence", "status", "notes"):
        if not isinstance(data[field], str):
            raise ValueError(f"{field} must be a string")
    if data["status"] not in ALLOWED_STATUS:
        raise ValueError(f"Invalid status: {data['status']!r}")
    if data["confidence"] not in ALLOWED_CONFIDENCE:
        raise ValueError(f"Invalid confidence: {data['confidence']!r}")
    if data["source_type"] not in ALLOWED_SOURCE_TYPES:
        raise ValueError(f"Invalid source_type: {data['source_type']!r}")
    status = data["status"]
    confidence = data["confidence"]
    reading = data["reading"]
    source = data["source"]
    if status == "pending":
        if reading or source or data["source_type"] or confidence != "unknown":
            raise ValueError("pending result must have empty reading/source/source_type and confidence=unknown")
    elif status == "verified":
        if confidence not in {"high", "medium"} or not reading or not source:
            raise ValueError("verified result requires reading/source and confidence high or medium")
    elif status == "review":
        if confidence != "review":
            raise ValueError("review result requires confidence=review")
        if reading and not source:
            raise ValueError("review result with reading requires a supporting source")
    return data


def request_openrouter(uuid, name, prompt, attempt):
    api_key = os.environ.get("OPENROUTER_API_KEY")
    if not api_key:
        raise RuntimeError("OPENROUTER_API_KEY is not set")
    payload = {
        "model": OPENROUTER_MODEL,
        "messages": [{"role": "user", "content": prompt}],
        "response_format": {"type": "json_object"},
        "tools": [{"type": "openrouter:web_search"}],
    }
    headers = {
        "Authorization": f"Bearer {api_key}",
        "Content-Type": "application/json",
        "HTTP-Referer": "https://github.com/wonderalpha404/vtuber-dictionary",
        "X-Title": "VTuber Dictionary Reading Research",
    }
    log(f"OPENROUTER REQUEST name={name} uuid={uuid} attempt={attempt}/{MAX_API_ATTEMPTS} model={OPENROUTER_MODEL} web_search=true")
    started = time.monotonic()
    try:
        response = requests.post(OPENROUTER_URL, headers=headers, json=payload, timeout=(CONNECT_TIMEOUT, READ_TIMEOUT))
    except requests.exceptions.RequestException as exc:
        elapsed = time.monotonic() - started
        raise RuntimeError(f"OpenRouter request error after {elapsed:.1f}s: {exc}") from exc
    elapsed = time.monotonic() - started
    log(f"OPENROUTER HTTP RESPONSE name={name} uuid={uuid} attempt={attempt}/{MAX_API_ATTEMPTS} status={response.status_code} elapsed={elapsed:.1f}s bytes={len(response.content)}")
    if response.status_code != 200:
        raise RuntimeError(f"OpenRouter HTTP status {response.status_code}: {response.text[:1000]}")
    try:
        data = response.json()
    except json.JSONDecodeError as exc:
        raise RuntimeError(f"Failed to parse OpenRouter HTTP response as JSON: {exc}") from exc
    choices = data.get("choices")
    if not isinstance(choices, list) or not choices:
        raise RuntimeError("OpenRouter response contains no choices")
    message = choices[0].get("message")
    if not isinstance(message, dict):
        raise RuntimeError("OpenRouter response contains no message object")
    if message.get("refusal"):
        raise RuntimeError("OpenRouter returned a refusal")
    content = message.get("content")
    if not isinstance(content, str):
        raise RuntimeError("OpenRouter message content is not a string")
    return content


def research(uuid, name):
    started_at = utc_now()
    log(f"RESEARCH START uuid={uuid} name={name}")
    if is_kana_only_name(name):
        try:
            result = make_deterministic_result(uuid, name)
            upsert_result(result)
            log(f"RESULT SAVED name={name} uuid={uuid} reading={result['reading']} status=verified confidence=")
            return 0
        except Exception as exc:
            log(f"DETERMINISTIC PROCESSING FAILED name={name} uuid={uuid} error_type={type(exc).__name__} message={exc}")
            existing = None
            try:
                existing = get_existing_result(uuid)
            except Exception:
                pass
            if not (isinstance(existing, dict) and existing.get("last_attempt_result") == "success"):
                try:
                    upsert_result(make_failure_record(uuid, name, started_at, existing))
                except Exception as save_exc:
                    log(f"FAILURE STATE SAVE FAILED: {save_exc}")
            return 1

    prompt = build_prompt(uuid, name)
    last_error = None
    for attempt in range(1, MAX_API_ATTEMPTS + 1):
        try:
            content = request_openrouter(uuid, name, prompt, attempt)
            data = validate_result(extract_json_object(content), uuid, name)
            now = utc_now()
            result = {
                "uuid": uuid, "name": name, "reading": data["reading"],
                "source": data["source"], "source_type": data["source_type"],
                "confidence": data["confidence"], "status": data["status"], "notes": data["notes"],
                "checked_at": now, "last_attempted_at": now, "last_attempt_result": "success",
            }
            upsert_result(result)
            log(f"RESULT SAVED name={name} uuid={uuid} reading={result['reading']} status={result['status']} confidence={result['confidence']}")
            return 0
        except Exception as exc:
            last_error = exc
            log(f"RESEARCH ATTEMPT FAILED name={name} uuid={uuid} attempt={attempt}/{MAX_API_ATTEMPTS} error_type={type(exc).__name__} message={exc}")
            if attempt < MAX_API_ATTEMPTS:
                delay = RETRY_DELAYS[attempt - 1]
                log(f"RESEARCH RETRY SCHEDULED next_attempt={attempt + 1}/{MAX_API_ATTEMPTS} wait={delay}s")
                time.sleep(delay)

    existing = None
    try:
        existing = get_existing_result(uuid)
    except Exception as exc:
        log(f"EXISTING RESULT LOAD FAILED name={name} uuid={uuid} error_type={type(exc).__name__} message={exc}")
    if not (isinstance(existing, dict) and existing.get("last_attempt_result") == "success"):
        try:
            upsert_result(make_failure_record(uuid, name, started_at, existing))
            log(f"FAILURE STATE SAVED name={name} uuid={uuid} status=pending last_attempt_result=technical_error")
        except Exception as save_exc:
            log(f"FAILURE STATE SAVE FAILED name={name} uuid={uuid} error_type={type(save_exc).__name__} message={save_exc}")
    log(f"RESEARCH FAILED name={name} uuid={uuid} error_type={type(last_error).__name__ if last_error else 'unknown'} message={last_error if last_error else 'unknown error'}")
    return 1


def main():
    if len(sys.argv) != 3:
        print("Usage: python scripts/research_one_vtuber.py <uuid> <name>", file=sys.stderr)
        return 2
    return research(sys.argv[1], sys.argv[2])


if __name__ == "__main__":
    sys.exit(main())
